name: ansible syntax check

on:
  pull_request:
    branches:
      - main
    paths:
      - "ansible/**"

jobs:
  ansible:
    name: "Ansible"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Ansible syntax check
        run: ansible-playbook -i localhost, -c local site.yml --syntax-check
        working-directory: ./ansible
